# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aleksei_Varaksin_vk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aleksei_Varaksin_vk
  pod 'Alamofire', '~> 5.0.0-rc.3'
  pod 'Kingfisher', '~> 5.11.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'RealmSwift', '~> 4.1.1'

end
