# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Aleksei_Varaksin_vk' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Aleksei_Varaksin_vk
  pod 'Alamofire', '~> 4.0'
  pod 'Kingfisher', '~> 5.11.0'
  pod 'SwiftyJSON', '~> 5.0.0'
  pod 'RealmSwift', '~> 4.1.1'
  pod 'PromiseKit', '~> 6.13.1'
  pod 'PromiseKit/Alamofire'

end
